name: Cart CI-Dev Branch
on:
  push:
    branches:
      - '!main'
      - 'dev*'
jobs:
  call-common:
    uses: manjudevopszone/github-actions-reusable/.github/workflows/ci-dev.yaml@main
    with:
      component: cart