name: Cart CI-Main Branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  call-common:
    uses: manjudevopszone/github-actions-reusable/.github/workflows/ci-auth-service.yaml@main
    with:
      component: cart